// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/lizaiganshenmo/mixStew/cmd/api/biz/rpc"
	config "github.com/lizaiganshenmo/mixStew/cmd/api/configs"
	"github.com/lizaiganshenmo/mixStew/cmd/api/resource"
)

func Init() {
	// conf init
	config.Init()
	// rpc init
	rpc.Init()
	// resource 全局变量初始化 包含log
	resource.Init()
}

func main() {
	Init()

	h := server.Default()

	register(h)
	h.Spin()
}
