// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/lizaiganshenmo/mixStew/cmd/api/biz/handler"
	"github.com/lizaiganshenmo/mixStew/cmd/api/biz/middleware"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	r.POST("/users/login", middleware.AuthMiddleware.LoginHandler)
	r.POST("/users", handler.RegisterUser)                                      // 根据realworld specs 定义路由
	r.GET("/user", middleware.AuthMiddleware.MiddlewareFunc(), handler.GetUser) // 查询当前用户信息
	r.PUT("/user", handler.UpdateUser)                                          // 更新用户信息

	// follow
	profileGroup := r.Group("/profiles", middleware.AuthMiddleware.MiddlewareFunc())
	profileGroup.POST("/:follow_uid/follow", handler.Follow)
	profileGroup.DELETE("/:follow_uid/follow", handler.UnFollow)
	profileGroup.GET("/:follow_uid", handler.GetProfile)

}
