// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/requestid"
	handler "github.com/lizaiganshenmo/mixStew/cmd/api/biz/handler"
	"github.com/lizaiganshenmo/mixStew/cmd/api/biz/middleware"
	"github.com/lizaiganshenmo/mixStew/library/constants"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	// gen request_id for log
	r.Use(requestid.New(
		requestid.WithCustomHeaderStrKey(constants.RequestIdKey),
	))
	r.Use(middleware.AddMetaInfo()) // add meta info for trans

	r.GET("/ping", handler.Ping)

	r.POST("/users/login", middleware.AuthMiddleware.LoginHandler)
	r.POST("/users", handler.RegisterUser)                                      // 根据realworld specs 定义路由
	r.GET("/user", middleware.AuthMiddleware.MiddlewareFunc(), handler.GetUser) // 查询当前用户信息
	r.PUT("/user", handler.UpdateUser)                                          // 更新用户信息

	// follow
	profileGroup := r.Group("/profiles", middleware.AuthMiddleware.MiddlewareFunc())
	profileGroup.POST("/:follow_uid/follow", handler.Follow)
	profileGroup.DELETE("/:follow_uid/follow", handler.UnFollow)
	profileGroup.GET("/:follow_uid", handler.GetProfile)

}
